# Generated by Django 2.2.7 on 2019-11-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20191128_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_celery',
            field=models.CharField(default='xx', max_length=100),
        ),
    ]
