# Generated by Django 2.2.7 on 2019-11-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_tasks_task_celery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_celery',
            field=models.TextField(default='xx', max_length=100),
        ),
    ]
