# Generated by Django 2.2.7 on 2019-11-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20191128_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='task_celery',
        ),
    ]
