# Generated by Django 2.2.7 on 2019-11-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_remove_tasks_task_celery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_celery',
            field=models.CharField(default='xx', max_length=100),
        ),
    ]
